# crates/connector-mock/Cargo.toml
[package]
name = "connector-mock"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
async-trait = "0.1"
uuid = { version = "1", features = ["v4"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2.0.16"
