[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {  version = "1", features = ["derive"] , workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
async-trait = "0.1"